version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dira
    ports:
      - "3306:3306"
    volumes:
      - D:\DEV\Docker\Volumes\dira:/var/lib/mysql

volumes:
  mysql_data:
